# Generated by Django 3.2.12 on 2022-04-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='project',
            new_name='emp',
        ),
    ]
