# Generated by Django 3.2.12 on 2022-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_project_user_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Out of work', 'Out of work'), ('Homemaker', 'Homemaker')], max_length=70),
        ),
    ]
